services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    #
    # SESSION
    #

    Pimcore\Bundle\EcommerceFrameworkBundle\Tools\SessionConfigurator:
        public: false
        deprecated:
            message: 'The "%service_id%" service is deprecated, use SessionBagListener instead.'
            package: pimcore/pimcore
            version: 10.5

    #
    # INSTALLER
    #

    pimcore.ecommerceframework.installer: '@Pimcore\Bundle\EcommerceFrameworkBundle\Tools\Installer'
    Pimcore\Bundle\EcommerceFrameworkBundle\Tools\Installer:
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreEcommerceFrameworkBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\EcommerceFrameworkBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

