services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true



    Pimcore\Bundle\PersonalizationBundle\Targeting\Maintenance\TargetingStorageTask: ~
    Pimcore\Bundle\PersonalizationBundle\Targeting\Service\TargetingEnableService: ~
