services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pimcore\DataObject\ClassBuilder\ClassBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\ClassBuilder'

    Pimcore\DataObject\ClassBuilder\FieldCollectionClassBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\FieldCollectionClassBuilder'

    Pimcore\DataObject\ClassBuilder\FieldDefinitionBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\FieldDefinitionBuilder'

    Pimcore\DataObject\ClassBuilder\FieldDefinitionDocBlockBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\FieldDefinitionDocBlockBuilder'

    Pimcore\DataObject\ClassBuilder\FieldDefinitionPropertiesBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\FieldDefinitionPropertiesBuilder'

    Pimcore\DataObject\ClassBuilder\ListingClassBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\ListingClassBuilder'

    Pimcore\DataObject\ClassBuilder\ListingClassFieldDefinitionBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\ListingClassFieldDefinitionBuilder'

    Pimcore\DataObject\ClassBuilder\ObjectBrickClassBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\ObjectBrickClassBuilder'

    Pimcore\DataObject\ClassBuilder\ObjectBrickContainerClassBuilderInterface:
        class: 'Pimcore\DataObject\ClassBuilder\ObjectBrickContainerClassBuilder'

    Pimcore\DataObject\ClassBuilder\PHPClassDumperInterface:
        class: 'Pimcore\DataObject\ClassBuilder\PHPClassDumper'

    Pimcore\DataObject\ClassBuilder\PHPFieldCollectionClassDumperInterface:
        class: 'Pimcore\DataObject\ClassBuilder\PHPFieldCollectionClassDumper'

    Pimcore\DataObject\ClassBuilder\PHPObjectBrickClassDumperInterface:
        class: 'Pimcore\DataObject\ClassBuilder\PHPObjectBrickClassDumper'

    Pimcore\DataObject\ClassBuilder\PHPObjectBrickContainerClassDumperInterface:
        class: 'Pimcore\DataObject\ClassBuilder\PHPObjectBrickContainerClassDumper'
    
