services:
    Pimcore\Messenger\Handler\SendNewsletterHandler:
        arguments:
            - '%pimcore.config%'
            - '@pimcore.newsletter.address_source_adapter.factories'
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\ClearThumbnailsHandler:
        tags:
            - { name: messenger.message_handler }

    Pimcore\Messenger\Handler\VideoConvertHandler:
        tags:
            - { name: messenger.message_handler }
