services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #
    Pimcore\Bundle\SeoBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreSeoBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\SeoBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']


    #
    # EVENTLISTENER
    #

    Pimcore\Bundle\SeoBundle\EventListener\ResponseExceptionListener: ~
    Pimcore\Bundle\SeoBundle\EventListener\UrlSlugUpdateListener: ~
    Pimcore\Bundle\SeoBundle\EventListener\PageDocumentListener: ~
    # Sitemap listener delegating work to configured generators
    Pimcore\Bundle\SeoBundle\EventListener\SitemapGeneratorListener: ~
    Pimcore\Bundle\SeoBundle\EventListener\RoutingListener: ~


    #
    # ELEMENTS
    #
    # Services valid for all elements

    # Generic URL generator accepting a path
    Pimcore\Bundle\SeoBundle\Sitemap\UrlGeneratorInterface: '@Pimcore\Bundle\SeoBundle\Sitemap\UrlGenerator'
    Pimcore\Bundle\SeoBundle\Sitemap\UrlGenerator: ~

    # Filters
    Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PublishedFilter: ~
    Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PropertiesFilter: ~

    # Processors
    Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\ModificationDateProcessor: ~
    Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\PropertiesProcessor: ~



    #
    # DOCUMENTS
    #
    # Services valid for documents

    # Default filters for DocumentTreeGenerator

    Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\DocumentTypeFilter: ~
    Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\SiteRootFilter: ~

    # Default document URL generator
    Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentUrlGeneratorInterface: '@Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentUrlGenerator'
    Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentUrlGenerator: ~

    # Default document tree generator
    Pimcore\Bundle\SeoBundle\Sitemap\Document\DocumentTreeGenerator:
        arguments:
            $filters:
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PublishedFilter'
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Element\Filter\PropertiesFilter'
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\DocumentTypeFilter'
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Document\Filter\SiteRootFilter'
            $processors:
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\ModificationDateProcessor'
                - '@Pimcore\Bundle\SeoBundle\Sitemap\Element\Processor\PropertiesProcessor'

    # redirect handler used to handle redirects before/after routing
    Pimcore\Bundle\SeoBundle\Redirect\RedirectHandler:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: routing }

    #
    # REDIRECTS Export
    #
    Pimcore\Bundle\SeoBundle\Redirect\Csv: ~