services:
    minio_client:
        class: 'Aws\S3\S3Client'
        arguments:
            -  endpoint: 'http://127.0.0.1:9001'
               accessKeyId: '%env(MINIO_ACCESS_KEY)%'
               accessKeySecret: '%env(MINIO_SECRET_KEY)%'

flysystem:
    storages:
        pimcore.asset.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'asset'
        pimcore.asset_cache.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'asset_cache'
        pimcore.thumbnail.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'thumbnail'
        pimcore.version.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'version'
        pimcore.recycle_bin.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'recycle_bin'
        pimcore.admin.storage:
            adapter: 'local'
            visibility: public
            options:
                client: 'minio_client'
                bucket: 'admin'