pimcore:
    general:
        timezone: Europe/Berlin
        path_variable: ''
        domain: pimcore-test.dev
        redirect_to_maindomain: false
        language: en
        validLanguages: 'en,de'
        fallbackLanguages:
            en: ''
            de: ''
        defaultLanguage: ''
        disableusagestatistics: false
        debug: true
        debug_ip: ''
        http_auth:
            username: ''
            password: ''
        debug_admin_translations: false
        devmode: false
        instanceIdentifier: ''
        show_cookie_notice: false
    documents:
        versions:
            days: null
            steps: 10
        error_pages:
            default: /error
        createredirectwhenmoved: false
        allowtrailingslash: 'no'
        generatepreview: true
    objects:
        versions:
            days: null
            steps: 10
    assets:
        versions:
            days: null
            steps: 10
        icc_rgb_profile: ''
        icc_cmyk_profile: ''
        hide_edit_image: false
        disable_tree_preview: false
    services:
        google:
            client_id: ''
            email: ''
            simpleapikey: ''
            browserapikey: ''
    cache:
        enabled: false
        lifetime: null
        excludePatterns: ''
        excludeCookie: ''
    outputfilters:
        less: false
        lesscpath: ''
    webservice:
        enabled: true
    httpclient:
        adapter: Zend_Http_Client_Adapter_Socket
        proxy_host: ''
        proxy_port: ''
        proxy_user: ''
        proxy_pass: ''
    email:
        sender:
            name: pimcore
            email: pimcore@example.com
        return:
            name: pimcore
            email: pimcore@example.com
        method: sendmail
        debug:
            emailaddresses: ''
    newsletter:
        sender:
            name: ''
            email: ''
        return:
            name: ''
            email: ''
        method: sendmail
        debug: null
        usespecific: true
    applicationlog:
        mail_notification:
            send_log_summary: false
            filter_priority: null
            mail_receiver: ''
        archive_treshold: '30'
        archive_alternative_database: ''
pimcore_admin:
    branding:
        color_login_screen: ''
        color_admin_interface: ''
        loginscreencustomimage: ''
swiftmailer:
    mailers:
        pimcore_mailer:
            transport: smtp
            delivery_addresses:
                emailaddresses: ''
            host: ''
            username: ''
            password: ''
            port: ''
            encryption: null
            auth_mode:
        newsletter_mailer:
            transport: sendmail
            delivery_addresses: null
            host: ''
            username: ''
            password: null
            port: ''
            encryption: null
            auth_mode: null
