services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #
    Pimcore\Bundle\StaticRoutesBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('StaticRoutesBundle')"

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    Pimcore\Bundle\StaticRoutesBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]