# Pimcore
pimcore_admin:

    session:
        attribute_bags:
            - pimcore_admin
            - pimcore_objects
            - pimcore_copy
            - pimcore_gridconfig
            - pimcore_importconfig

    # the following routes won't be double checked for authentication
    # this usually applies to login routes
    unauthenticated_routes:
        - { route: pimcore_settings_display_custom_logo }
        - { route: pimcore_admin_login }
        - { route: pimcore_admin_webdav }

    translations:
        path: "@PimcoreCoreBundle/translations"

    user:
        default_key_bindings:
            save:
                key: 'S'
                ctrl: true
            publish:
                key: 'P'
                ctrl: true
                shift: true
            unpublish:
                key: 'U'
                ctrl: true
                shift: true
            rename:
                key: 'R'
                alt: true
                shift: true
            refresh:
                key: 't'
            openAsset:
                key: 'A'
                ctrl: true
                shift: true
            openObject:
                key: 'O'
                ctrl: true
                shift: true
            openDocument:
                key: 'D'
                ctrl: true
                shift: true
            openClassEditor:
                key: 'C'
                ctrl: true
                shift: true
            openInTree:
                key: 'L'
                ctrl: true
                shift: true
            showMetaInfo:
                key: 'I'
                alt: true
            searchDocument:
                key: 'W'
                alt: true
            searchAsset:
                key: 'A'
                alt: true
            searchObject:
                key: 'O'
                alt: true
            showElementHistory:
                key: 'H'
                alt: true
            closeAllTabs:
                key: 'T'
                alt: true
            searchAndReplaceAssignments:
                key: 'S'
                alt: true
            redirects:
                key: 'R'
                ctrl: false
                alt: true
            sharedTranslations:
                key: 'T'
                ctrl: true
                alt: true
            recycleBin:
                key: 'R'
                ctrl: true
                alt: true
            notesEvents:
                key: 'N'
                ctrl: true
                alt: true
            applicationLogger:
                key: 'L'
                ctrl: true
                alt: true
            reports:
                key: 'M'
                ctrl: true
                alt: true
            tagManager:
                key: 'H'
                ctrl: true
                alt: true
            seoDocumentEditor:
                key: 'S'
                ctrl: true
                alt: true
            robots:
                key: 'J'
                ctrl: true
                alt: true
            httpErrorLog:
                key: 'O'
                ctrl: true
                alt: true
            customReports:
                key: 'C'
                ctrl: true
                alt: true
            tagConfiguration:
                key: 'N'
                ctrl: true
                alt: true
            users:
                key: 'U'
                ctrl: true
                alt: true
            roles:
                key: 'P'
                ctrl: true
                alt: true
            clearAllCaches:
                key: 'Q'
                ctrl: false
                alt: true
            clearDataCache:
                key: 'C'
                ctrl: false
                alt: true
            quickSearch:
                key: 'F'
                ctrl: true
                shift: true

# adds support for admin related routes that will be used to determine the request context in PimcoreContextGuesser
pimcore:
    web_profiler:
        toolbar:
            excluded_routes:
                - { path: '^/admin/asset/image-editor' }
    context:
        admin:
            routes:
                - { path: ^/admin(/.*)?$ }
                - { route: ^pimcore_admin_ }
    security:
        password_hasher_factories:
            Pimcore\Bundle\AdminBundle\Security\User\User: pimcore_admin.security.password_hasher_factory


flysystem:
    storages:
        pimcore.admin.storage:
            # Storage for shared admin resources, such as the user avatar, custom logos, ...
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'

twig:
    globals:
        pimcore_csrf: '@Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler'
        pimcore_csp: '@Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler'