# Pimcore
pimcore_admin:

    session:
        attribute_bags:
            - pimcore_admin
            - pimcore_objects
            - pimcore_copy
            - pimcore_gridconfig
            - pimcore_importconfig

    # the following routes won't be double checked for authentication
    # this usually applies to login routes
    unauthenticated_routes:
        - { route: pimcore_settings_display_custom_logo }
        - { route: pimcore_admin_login }
        - { route: pimcore_admin_webdav }

    translations:
        path: "@PimcoreCoreBundle/translations"

    user:
        default_key_bindings:
            save:
                key: 'S'
                method: save
                ctrl: true
            publish:
                key: 'P'
                method: publish
                ctrl: true
                shift: true
            unpublish:
                key: 'U'
                method: unpublish
                ctrl: true
                shift: true
            rename:
                key: 'R'
                method: rename
                alt: true
                shift: true
            refresh:
                key: 't'
                method: refresh
            open_asset:
                key: 'A'
                method: openAsset
                ctrl: true
                shift: true
            open_object:
                key: 'O'
                method: openObject
                ctrl: true
                shift: true
            open_document:
                key: 'D'
                method: openDocument
                ctrl: true
                shift: true
            open_class_editor:
                key: 'C'
                method: openClassEditor
                ctrl: true
                shift: true
            open_in_tree:
                key: 'L'
                method: openInTree
                ctrl: true
                shift: true
            show_meta_info:
                key: 'I'
                method: showMetaInfo
                alt: true
            search_document:
                key: 'W'
                method: searchDocument
                alt: true
            search_asset:
                key: 'A'
                method: searchAsset
                alt: true
            search_object:
                key: 'O'
                method: searchObject
                alt: true
            show_element_history:
                key: 'H'
                method: showElementHistory
                alt: true
            close_all_tabs:
                key: 'T'
                method: closeAllTabs
                alt: true
            search_and_replace_assignments:
                key: 'S'
                method: searchAndReplaceAssignments
                alt: true
            redirects:
                key: 'R'
                method: redirects
                ctrl: false
                alt: true
            shared_translations:
                key: 'T'
                method: sharedTranslations
                ctrl: true
                alt: true
            recycle_bin:
                key: 'R'
                method: recycleBin
                ctrl: true
                alt: true
            notes_events:
                key: 'N'
                method: notesEvents
                ctrl: true
                alt: true
            application_logger:
                key: 'L'
                method: applicationLogger
                ctrl: true
                alt: true
            reports:
                key: 'M'
                method: reports
                ctrl: true
                alt: true
            tag_manager:
                key: 'H'
                method: tagManager
                ctrl: true
                alt: true
            seo_document_editor:
                key: 'S'
                method: seoDocumentEditor
                ctrl: true
                alt: true
            robots:
                key: 'J'
                method: robots
                ctrl: true
                alt: true
            http_error_log:
                key: 'O'
                method: httpErrorLog
                ctrl: true
                alt: true
            custom_reports:
                key: 'C'
                method: customReports
                ctrl: true
                alt: true
            tag_configuration:
                key: 'N'
                method: tagConfiguration
                ctrl: true
                alt: true
            users:
                key: 'U'
                method: users
                ctrl: true
                alt: true
            roles:
                key: 'P'
                method: roles
                ctrl: true
                alt: true
            clear_all_caches:
                key: 'Q'
                method: clearAllCaches
                ctrl: false
                alt: true
            clear_data_cache:
                key: 'C'
                method: clearDataCaches
                ctrl: false
                alt: true
            quick_search:
                key: 'F'
                method: quickSearch
                ctrl: true
                shift: true

# adds support for admin related routes that will be used to determine the request context in PimcoreContextGuesser
pimcore:
    web_profiler:
        toolbar:
            excluded_routes:
                - { path: '^/admin/asset/image-editor' }
    context:
        admin:
            routes:
                - { path: ^/admin(/.*)?$ }
                - { route: ^pimcore_admin_ }
    security:
        password_hasher_factories:
            Pimcore\Bundle\AdminBundle\Security\User\User: pimcore_admin.security.password_hasher_factory


flysystem:
    storages:
        pimcore.admin.storage:
            # Storage for shared admin resources, such as the user avatar, custom logos, ...
            adapter: 'local'
            visibility: private
            options:
                directory: '%kernel.project_dir%/var/admin'

twig:
    globals:
        pimcore_csrf: '@Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler'
        pimcore_csp: '@Pimcore\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler'