
name: "Codeception Tests"

on:
    pull_request:
        branches:
            - "*.*"
            - "master"
    push:
        branches:
            - "*.*"
            - "master"
            - "*_actions"

env:
    PIMCORE_PROJECT_ROOT: ${{ github.workspace }}
    PIMCORE_ENVIRONMENT: test
    PIMCORE_TEST: 1
    PIMCORE_TEST_DB_DSN: "mysql://root@127.0.0.1:33006/pimcore_test"

jobs:
    codeception-tests:
        name: "Codeception tests"
        runs-on: "ubuntu-20.04"

        strategy:
            matrix:
                dependencies:
                    - "lowest"
                    - "highest"
                php-version:
                    - "7.4"

        services:
            mariadb:
                image: "mariadb:10.4"
                ports:
                    - 33006:3306
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v2"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "${{ matrix.php-version }}"

            - name: Verify MariaDB connection
              run: |
                  cp .github/ci/files/.my.cnf ~/.my.cnf
                  while ! mysqladmin ping --silent; do
                    sleep 1
                  done

            - name: "Database server infos"
              run: |
                  mysql -e "SELECT VERSION();"
                  mysql -e "CREATE DATABASE pimcore_test CHARSET=utf8mb4;"

            - name: "Setup Pimcore environment"
              run: |
                  .github/ci/scripts/setup-pimcore-environment.sh

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"

            - name: "Run Codeception"
              run: "vendor/bin/codecept run -c . -vvv --json"